apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: todo
  namespace: todo
spec:
  releaseName: todo
  chart:
    spec:
      chart: todo-app
      sourceRef:
        kind: HelmRepository
        name: todo
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    replicas: 1
